name: crm
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  # Business logic library
  bloc: ^8.1.3
  # Flutter library to load and cache network images
  cached_network_image: ^3.3.1
  # Cupertino style icons
  cupertino_icons: ^1.0.6
  # Functional programming library for Dart
  dartz: ^0.10.1
  # HTTP client for Dart
  dio: ^5.4.1
  # Equality comparisons for Dart
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  # State management library
  flutter_bloc: ^8.1.4
  # Localizations for Flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  # Flutter plugin for native splash screen
  flutter_native_splash: ^2.2.16
  # Flutter screen adaptation library
  flutter_screenutil: ^5.9.0
  # SVG rendering library for Flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  go_router: ^13.2.0
  # Flutter plugin for checking internet connectivity
  internet_connection_checker: ^1.0.0+1
  # Internationalization and localization library
  intl: ^0.18.1
  intl_utils: ^2.8.7
  latlong2: ^0.9.0
  # Flutter plugin for loading animation
  loading_animation_widget: ^1.2.1
  # Flutter plugin for logging
  logger: ^2.1.0
  # Flutter plugin for map luncher
  map_launcher: ^3.2.0
  # Flutter plugin for reading and writing simple key-value pairs
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  analyzer: ^6.4.1
  # Code generator for Flutter
  build_runner: ^2.4.8

  # Linter for Dart
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png

  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  generate: true
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/errors/
    - assets/images/empty-states/
    - assets/icons/

  # Fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
  class_name: S
  arb_dir: lib/l10n
  output_dir: lib/l10n
